### ISSUE TITLE
旗艦の艦種指定

### ISSUE THREAD

**Issue by solarlittle** [ruhiel/ExpeditionListPlugin#1]
お世話になっております
"北方航路海上護衛"など旗艦の艦種指定が判定されていません
とても見やすく重宝しているのでお暇なときに修正していただければ、と思います

**Comment by ruhiel** [comment]
@solarlittle issue立てありがとうございます。v1.0.4リリースにて対応しましたのでご確認いただければと思います。

**Comment by solarlittle** [comment]
こちらでも修正を確認しました
迅速な対応ありがとうございました
