### ISSUE TITLE
既知の不具合と意見

### ISSUE THREAD

**Issue by kancolleojisan** [ruhiel/ExpeditionListPlugin#4]
こんにちは。様々な有用なプラグインを公開してくださりありがとうございます。
まず多分現時点でのプルリクエスト込みでも恐らく修正されてないであろう不具合を指摘させて頂きます。C#は全くわかっていないに等しいのでお手柔らかにお願いいたします。

・艦隊対空値の計算に艤装分が反映されていない（多分）
「南西方面航空偵察作戦」が各種パラメータを満たしているにも関わらず「失敗」と表示されており、おかしいなーなんでだろうなーと思ってもprintfデバッグの仕方さえもわかっていないので手探りで突き止めました多分艤装分が反映されていないと思います。
ExpeditionInfo.csの該当部分を以下のように修正することで正常に反映されるようになりました。

        private bool SumAACheck(int index)
        {
            if (null == SumAA) return true;

            var sum_aa = KanColleClient.Current.Homeport.Organization.Fleets[index].Ships.Select(
                ship => ship.EquippedItems.Sum(s => s.Item.Info.AA)).Sum(); //装備対空値の合計
            return KanColleClient.Current.Homeport.Organization.Fleets[index].Ships.Select(s => s.AA).Sum(s => s.Current) + sum_aa >= SumAA;
        }

・一部の遠征名（特に南西方面航空偵察作戦）が途中までしか表示されない
プルリクエストでrenirisさんの修正されてらっしゃるような形で
Width="auto"　から　Width="132"　にするとピッタリ良い感じになりました。

以上2点不具合の報告になります。

続いて意見になります。
「旗艦艦種」は1文字か2文字で完結するものなので「旗艦」の2文字でも良いかなと、更に「必要艦種」の手前にあるとうっかり見過ごすのを防げるかなと思いました。
今回の新遠征へのご対応にあたり、既存の遠征の成功条件も追加してくださいまして感謝しております。しかしこれがもう少しまとめられるような気がしたので意見させて頂きます。
例えば「タンカー護衛任務」の
軽1 駆2 or 駆1 海防3 or 軽1 海防2 or 練1 海防2 or 護母1 海防2 or 護母1 駆2
こちらは
軽1/護母1 駆2/海防2 or 駆1 海防3 or 軽1/練1 海防2
まで短く出来ます。すると私の環境では家具箱まで表示出来るようになり少し嬉しい感じです。
（しかしこれを実現するには必要艦種を1つずつ評価するのではなく、ORしていってANDして判定するような形に管理方法を変更しなければ難しい感じになるのでしょうか・・・）

以上ご検討頂けましたら幸いです。

**Comment by ruhiel** [comment]
こんにちは。issue立てありがとうございます。
本件 v1.0.8 リリースにて対応致しましたのでご確認ください。

なお、上記の「タンカー護衛任務」の場合の編成表記は以下としました。

軽1駆2 駆1海防3 海防2軽1or練1 護母1駆2or海防2

以上です。

**Comment by kancolleojisan** [comment]
ご対応ありがとうございます。対空値計算における正常動作の方、確認させて頂きました。
また私の提示したものよりも読み易く、短い表示、素晴らしいです。ありがとうございます。
