### ISSUE TITLE
第◯パラ表示につきまして

### ISSUE THREAD

**Issue by kancolleojisan** [ruhiel/ExpeditionListPlugin#5]
こんにちは。続けざまに失礼します。
１つだけ気になったことがあります。今回◯×で条件判定を出してくださる形になっていますが、例えば対空は◯で対潜が×の時、「対空◯」までの表示でその後に続く文字列の存在に最初気付きませんでした。「◯なのに失敗とは・・・」と、これは慣れの問題でもあると思うのですが、もし可能でありましたら×が含まれる時、文字色や背景色などを赤色などに変えて頂ければ、その続きにエラーがあるという想像がし易いのではと感じました。
この辺り、何かしらのご検討を頂けましたら幸いです。

**Comment by ruhiel** [comment]
@kancolleojisan 
issue立てありがとうございます。

まず前提として、なにぶんスペースが限られているので情報をなるべく表示しつつ、見やすくというのは私の技術力では限界がありますｗ すみません。

本件ですが、×になったパラメータだけ出せば良いのかなと思います。
あと、第二成否と第二パラも分ける必要がないような気がしてきました。
ご意見をお聞かせいただければ幸いです。

**Comment by reniris** [comment]
横から失礼します
第？パラを作ったrenirisです

とりあえず意見を参考にしてテスト用プロジェクトに追加して
第？パラで×があるものを赤くしてみました
https://github.com/reniris/ExpeditionListPlugin/tree/ModUI
個人的には第？成否のツールチップに第？パラを表示するのもいいかなと思います
でもツールチップがあることを知らないと意味がないし難しいですよね
今のバージョンでも第？パラにはツールチップがついています
気になった場合はマウスオーバーしてみてください

**Comment by kancolleojisan** [comment]
@ruhiel さん
ありがとうございます。
すみません、ちょっと欲しがりすぎましたｗ
×の要素だけでも情報としては満足です。
第二成否と第二パラの統合につきましては、私の環境では必要艦艇をMAXに広げても家具箱まで入るという状態になり、これも大歓迎です。

@reniris さん
ありがとうございます。
ExpeditionListPluginUitest.exe、確認させて頂きました。
これは・・・見やすぅい！　ありがとうございます！
私も「失敗」のツールチップでも良いんじゃないのかなーから、やーそれでもマウス動かさないと何が足りないのかわからないのもアレかもなーみたいなことを色々考えまして、これはもしも可能であれば、なんですけれども、フィルター設定の項目に「第？パラ」のチェックボックスがあって、オフにしたら「失敗」の代わりに×要素を表示、オンにしたら「失敗」という表示と「第？パラ」の両方の表示という切り替えが出来れば、今回追加された多様な遠征条件を活用して遠征に出される方も、南西方面航空偵察作戦に低練度の子を入れる方も、みんな幸せになれるんじゃないかなって思いました。

もちろんどちらの方法でも個人的には非常に便利に感じますし、対応をご検討して頂けるというだけでとても幸せです。ありがとうございます。

**Comment by reniris** [comment]
第二成否と第二パラの統合＋ツールチップが一番楽だと思います。
だいぶ前のバージョンでは実際にそうなっていました。
フィルターはすごく面倒なので単純なON/OFF以外はやりたくないです。

**Comment by kancolleojisan** [comment]
ありがとうございます。
だいぶ前のバージョンでもそうなってたんですね。
それではそのような形を希望します。

**Comment by reniris** [comment]
統合版を作ってみました。
https://github.com/reniris/ExpeditionListPlugin/tree/ModUI
にあります。
プラグインへの反映はそのうちします。

**Comment by reniris** [comment]
チェックボックスでパラメータ成否の切り替えをできるようにしました。
https://github.com/reniris/ExpeditionListPlugin/tree/ModUI
まとまったらプラグイン側にマージします。

**Comment by kancolleojisan** [comment]
確認させて頂きました。お見事です。
しかし折角ご苦労してくださったのにこのような意見を申し上げるのは誠に恐縮ですが、この形であれば非表示にする必要はなく、常時表示にして見たい時だけ伸ばせば良いんじゃないかなーと・・・
なので可能でしたら内部的な動作として、VisibilityではなくWidthをいじる形にするのは難しいでしょうか。
こうしますと本来の表示非表示のイメージにあった動作になるのではないかと思います。
またその場合、赤く表示する必要もなくなると思います。見た目的にも落ち着くかなーと。

**Comment by reniris** [comment]
とりあえずチェックボックスなしで反映させます。
もうしばらくお待ちください。

**Comment by kancolleojisan** [comment]
ありがとうございます。
お待ちしております。

**Comment by reniris** [comment]
プルリクエストを投げました。
https://github.com/reniris/ExpeditionListPlugin/tree/ModUI
にソースがあります。

**Comment by kancolleojisan** [comment]
ありがとうございます。動作確認させて頂きました。

**Comment by ruhiel** [comment]
@kancolleojisan @reniris 
マージしてリリースしました。

https://github.com/ruhiel/ExpeditionListPlugin/releases/tag/v1.0.9

**Comment by kancolleojisan** [comment]
ありがとうございます。動作の方、確認させて頂きました。
見やすくなりました。感謝です。
